### PR TITLE
The plugin can scan for main class

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
Okay this requires a new fmp release

**Comment by rhuss** [comment]
hmm, not sure whether its due to the fix from yesterday, because in this case the generator is already running (whether the java-exec-generator was a race condition).

Will do a release of f-m-p tomorrow and then fix these quickstarts, too.

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
[merge]

**Pull request merged**
